"""Abstract graph backend interface."""
from abc import ABC, abstractmethod
from typing import Any

class GraphBackend(ABC):
    @abstractmethod
    def add_node(self, name: str, label: str, **props) -> None: ...
    @abstractmethod
    def add_edge(self, source: str, target: str, rel_type: str, **props) -> None: ...
    @abstractmethod
    def get_node(self, name: str) -> dict | None: ...
    @abstractmethod
    def get_edges(self, source: str = None, target: str = None, rel_type: str = None) -> list[dict]: ...
    @abstractmethod
    def query(self, pattern: str, **params) -> list[dict]: ...
    @abstractmethod
    def clear(self) -> None: ...
    @abstractmethod
    def node_count(self) -> int: ...
    @abstractmethod
    def edge_count(self) -> int: ...
